if(NOT DEFINED SCP_SOLVER_SDK_SOURCE_DIR OR "${SCP_SOLVER_SDK_SOURCE_DIR}" STREQUAL "")
  message(FATAL_ERROR "SCP_SOLVER_SDK_SOURCE_DIR is required.")
endif()

file(READ "${SCP_SOLVER_SDK_SOURCE_DIR}/install.ps1" _install_ps1)
file(READ "${SCP_SOLVER_SDK_SOURCE_DIR}/install.sh" _install_sh)
file(READ "${SCP_SOLVER_SDK_SOURCE_DIR}/examples/smoke/run.sh" _smoke_sh)

string(FIND "${_install_ps1}" [=[Remove-Item -LiteralPath $buildRoot]=] _ps_build_clean)
if(_ps_build_clean EQUAL -1)
  message(FATAL_ERROR "install.ps1 no longer removes the SDK build tree for -Clean.")
endif()
string(FIND "${_install_ps1}" [=[Remove-Item -LiteralPath $installRoot]=] _ps_release_clean)
if(NOT _ps_release_clean EQUAL -1)
  message(FATAL_ERROR "install.ps1 -Clean must not delete the existing release directory.")
endif()

string(FIND "${_install_sh}" [=[rm -rf -- "${build_root}"]=] _sh_build_clean)
if(_sh_build_clean EQUAL -1)
  message(FATAL_ERROR "install.sh no longer removes the SDK build tree for --clean.")
endif()
string(FIND "${_install_sh}" [=[rm -rf -- "${build_root}" "${install_dir}"]=] _sh_release_clean)
if(NOT _sh_release_clean EQUAL -1)
  message(FATAL_ERROR "install.sh --clean must not delete the existing release directory.")
endif()

string(FIND "${_smoke_sh}" [=[identity="$("${executables[0]}" --solver-info)"]=] _quoted_solver_info)
if(_quoted_solver_info EQUAL -1)
  message(FATAL_ERROR "run.sh must quote the discovered executable for --solver-info.")
endif()
